spring:
  application:
    name: springboot-redis-demo
  redis:
    host: 127.0.0.1
    port: 6379
    password: 12345678
    lettuce:
      pool:
#        一下均为默认值
#        连接池最大连接数
        max-active: 8
#        连接池最大阻塞时间，负数为无限制
        max-wait: -1
#        连接池最大空闲连接数
        max-idle: 8
#        连接池最小空闲连接数
        min-idle: 0
server:
  port: 8090
  servlet:
    context-path: /myApplication
